### PR TITLE
Security patch (follow-redirects) 2.4.4

### PR DESCRIPTION
**Pull request by Randy424**
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>
regarding: https://github.com/stolostron/backlog/issues/21771

- Used npm update follow-redirects to push follow-redirects to version 1.14.8, I wanted to avoid additional version changes to other dependencies, from an `npm audit fix`

### CODE REVIEW

**Comment by Randy424** [comment]
/hold
...will hold for 2.4.3 z-stream.

**Comment by Randy424** [comment]
By updating PR with another `npm audit fix` we now cover https://github.com/stolostron/backlog/issues/20620
FYI @KevinFCormier

**Comment by KevinFCormier** [comment]
Obsolete; all updates addressed by #1426

**Pull request closed without merging**
