### PR TITLE
Update old Travis files

### PR DESCRIPTION
**Pull request by KevinFCormier**
Signed-off-by: Kevin Cormier <kcormier@redhat.com>

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@schmidtd suggested removing these might fix a problem we're having with the application-ui-tests image.

**Comment by KevinFCormier** [comment]
@Kyl-Bempah Will hold this PR for now.

**Review by fxiang1 — APPROVED** [review]
LGTM

**Review by chenz4027 — APPROVED** [review]
lgtm

**Pull request merged**
