### PR TITLE
Update the version to fix ansible operator failure

### PR DESCRIPTION
**Pull request by chenz4027**
Signed-off-by: Maggie Chen <magchen@redhat.com>

### CODE REVIEW

**Comment by chenz4027** [comment]
Seems like 2.3 is no longer experiencing this issue. Closing the PR.
image

**Comment by KevinFCormier** [comment]
@chenz4027 Did you compare the OCP versions between canaries that hit the problem and thos that did not?

**Comment by chenz4027** [comment]
@KevinFCormier Ah good idea - no I haven't done so. Will investigate.

**Comment by chenz4027** [comment]
Thanks to @Kyl-Bempah , @KevinFCormier there are some charts that are very informative. 
image
image
With the help from Kyl, who filter through the latter chart filtering on the versions seen in the former chart and I notice the bulk of the errors are on 4.9

**Pull request closed without merging**
