### PR TITLE
Placement yaml fix

### PR DESCRIPTION
**Pull request by Randy424**
regarding: https://github.com/stolostron/backlog/issues/21728 (extended to 2.4.5)

Tested cases:

- Create app, choose git as a repo source, add new placement, change app name (should update placement reference)
- Create app, choose git as a repo source, select an existing placement, change app name (should not update existing placement name)
- Create app, choose git as repo source, select "select an existing placement", combobox should be empty
- Create a multi app subscription with two subscriptions, delete the first subscription, change the placement of the remaining subscription to the placement created for the first subscription.

### CODE REVIEW

**Comment by Randy424** [comment]
/hold 
test failure

**Comment by Randy424** [comment]
Thanks, I was going to mention at scrum that the new failures seem unrelated to the PR changes. Seems like running the e2e solved the issue?

Also, the PR is now in need of another review @KevinFCormier @chenz4027

**Review by chenz4027 — APPROVED** [review]
lgtm, thanks Randy!

**Pull request merged**
