### PR TITLE
fix bugs

### PR DESCRIPTION
**Pull request by jeswanke**
Signed-off-by: John Swanke <jswanke@redhat.com>

does #stolostron/backlog#19848
does #stolostron/backlog#18550

### CODE REVIEW

**Comment by KevinFCormier** [comment]
Verified that this addresses both bugs. We will need to get a good E2E test run though.

**Comment by jeswanke** [comment]
> Verified that this addresses both bugs. We will need to get a good E2E test run though.

Looks like claim timeout

**Comment by KevinFCormier** [comment]
2.4.z stream is still closed

**Pull request merged**
